StephCald/Bar-Best-Friend

.gitignore
Gemfile
Gemfile.lock
app/models/establishment.rb
app/models/favorite.rb
app/models/review.rb
app/models/review_tag.rb
app/models/tag.rb
app/models/user.rb
app/views/layouts/application.html.erb
config/environments/development.rb
config/initializers/acts_as_favoritor.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20221217022102_devise_create_users.rb
db/migrate/20221217022103_create_tags.rb
db/migrate/20221217022621_create_establishments.rb
db/migrate/20221217022622_create_reviews.rb
db/migrate/20221217022623_create_review_tags.rb
db/migrate/20221217034027_add_admin_to_users.rb
db/migrate/20221217034054_add_username_to_users.rb
db/migrate/20221217035035_acts_as_favoritor_migration.rb
db/schema.rb
test/models/establishment_test.rb
test/models/review_tag_test.rb
test/models/review_test.rb
test/models/tag_test.rb
test/models/user_test.rb

- build up all models and migration files; 
- added favourites gem and devise gem as well;

build up models and migration files

---

app/views/pages/home.html.erb
db/seeds.rb

Users seed

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/establishment_controller.rb
app/controllers/pages_controller.rb
app/models/establishment.rb
app/views/pages/home.html.erb
db/seeds.rb
test/controllers/establishment_controller_test.rb

Updated the seed file and added text and containers on the home page

updated the seed file and added some text to the home page

---

app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

- added icons of categories
- made 4 icons in the same baseline and added spaces between each one

Adding icons of catergories

---

app/controllers/establishments_controller.rb
app/views/establishment/show.html.erb
app/views/establishments/show.html.erb
app/views/pages/home.html.erb

added an establishment show page

establishment show page

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_map.scss
app/controllers/establishments_controller.rb
app/javascript/application.js
app/javascript/controllers/address_autocomplete_controller.js
app/javascript/controllers/application.js
app/javascript/controllers/index.js
app/javascript/controllers/map_controller.js
app/models/establishment.rb
app/views/establishments/_info_window.html.erb
app/views/establishments/_new_form.html.erb
app/views/establishments/show.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
config/initializers/geocoder.rb
db/migrate/20230106234143_add_coordinates_to_establishments.rb
db/schema.rb
package.json
yarn.lock

Adding map

---

Gemfile
app/controllers/pages_controller.rb
app/models/establishment.rb
app/views/establishments/_info_window.html.erb
app/views/layouts/application.html.erb
app/views/pages/_info_window.html.erb
db/migrate/20230107010021_change_location_type_name.rb

still issues with the markers not being picked up in the markerValue target in the html.erb

still trying to get map markers working

---

app/controllers/application_controller.rb
app/controllers/establishments_controller.rb
app/controllers/favorites_controller.rb
app/policies/favorite_policy.rb
app/views/establishments/show.html.erb
app/views/favorites/index.html.erb
test/policies/favorite_policy_test.rb

- now able to see favorites list

fixed authorisation of favorites

---

app/controllers/establishments_controller.rb
app/policies/establishment_policy.rb
app/views/devise/sessions/new.html.erb
app/views/establishments/show.html.erb

- pundit was triggering to get the edit page... fixed this with @wclaudia840

fixed show page error caused by pundit

---

app/views/favorites/index.html.erb

- added a return button on the pawfect list

added a return button on pawfect list

---

app/controllers/establishments_controller.rb
app/models/establishment.rb
app/views/establishments/_new_form.html.erb
db/seeds.rb

Updated and added more seed files, fixed creating and adding new establishments and fixed _new_form error

Quick backend touches

---

app/views/pages/_info_window.html.erb

- added link to show page via the map markers

added links to the map marker popup

---

app/assets/stylesheets/pages/_home.scss
app/controllers/pages_controller.rb
app/models/establishment.rb
app/views/establishments/show.html.erb
app/views/pages/home.html.erb
db/seeds.rb

- filter icons by clicking 
- default search for cafes 
- resized icons/spacing between icons

able to do filters via adding a linkto and grabbing the params

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

-centered icon layout 
-spaces around for mobile and web view

centred, padding aroudn filter icons

---

app/controllers/establishments_controller.rb
app/views/pages/home.html.erb

- was missing a triangular bracket which made the home index page look weird

missing triangular bracket made the index look weird

---

app/views/pages/home.html.erb

- fixed bug : fav-button will not show for visitors;

fixed bug showing on the homepage of logging in

---

app/views/establishments/show.html.erb
app/views/pages/home.html.erb

captilized and show page and home page

capitalized location type on show and home pages

---

app/policies/user_policy.rb
app/views/shared/_navbar_dropdown.html.erb
test/policies/user_policy_test.rb

combined turbo data actions as this was the cause of the error

fixed log out bug

---

app/views/establishments/show.html.erb

added `current_user.present? && ` to line 19

added code to line 19

---

app/controllers/establishments_controller.rb
app/controllers/favorites_controller.rb
app/views/establishments/show.html.erb
app/views/favorites/index.html.erb
app/views/pages/home.html.erb

- changed fav-btn to white color;
- polished the fav list: 
1 showing text on the page to encourage user to add more establishment on the page; 
2 added a return button;

change fav-btn color and polish the fav-list

---

app/assets/stylesheets/components/_review_button.scss
app/assets/stylesheets/components/_wizard.scss
app/assets/stylesheets/pages/_home.scss
app/javascript/controllers/index.js
app/views/establishments/show.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

small changes to the establishment page

---

app/models/establishment.rb
app/views/establishments/_searchbar.html.erb
app/views/establishments/show.html.erb
app/views/favorites/index.html.erb
app/views/pages/home.html.erb

- realigned fav heart within home page, show page and in fav list

realigned the fav/unfav heart in container

---

app/assets/stylesheets/components/_icon.scss
app/controllers/establishments_controller.rb
app/views/establishments/_new_form.html.erb
app/views/establishments/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

Added comments and indents.
Please overwrite this for all files as the comments and indenting will not overwrite any other files.

indenting lines, removing divs that are not needed and fixing navbar

---

app/views/favorites/index.html.erb

slightly changes on the fav list

did slightly changes of the fav list

---

app/assets/stylesheets/components/_display_btn.scss
app/assets/stylesheets/components/_icon.scss
app/views/shared/_navbar.html.erb

fix changes

---

db/seeds.rb

hope this worked

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_icon.scss
app/assets/stylesheets/pages/_home.scss
app/views/establishments/show.html.erb
app/views/shared/_navbar_dropdown.html.erb

style changes

---

app/views/establishments/show.html.erb
app/views/pages/home.html.erb

- transparent fill when not favourited
- purple when favourited

changed purple heart filled on show and index page

---

app/views/favorites/index.html.erb

changed favourites list heart to purple

---

app/models/review.rb
app/views/pages/home.html.erb
db/seeds.rb

added a title that filters by location

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/pages_controller.rb
app/javascript/navbar.js
app/views/establishments/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

Changes color depending on the filter

selecting navbar changes
